#pragma once
#define PHYSICAL_DOMAIN_DIMENSION		2
#define GRID_FILE_TYPE					Gmsh
#define GRID_FILE_PATH					"RSC/Grid/Quad_10.msh"
#define GOVERNING_EQUATION_NAME			Linear_Advection
#define INITIAL_CONDITION_NAME			Sine_Wave
#define SPATIAL_DISCRETE_METHOD			FVM
#define NUMERICAL_FLUX_NAME				LLF
#define CFL								0.9
#define TIME_INTGRAL_METHOD				SSPRK33
#define END_CONDITION_NAME				Time
#define	END_CONDITION_CONSTANT			1.0
#define POST_FILE_NAME					"Test"
#define POST_CONDITION_NAME				Time
#define POST_CONDITION_CONSTANT			0.1





//FORMAT SETTER
#define FORMAT1(x,y) x ## _ ## y ## D
#define SET_FORMAT1(x,y) FORMAT1(x,y) 
#define FORMAT2(x,y) x ## _ ## y 
#define SET_FORMAT2(x,y) FORMAT2(x,y)

//USING MACRO
//FORMAT1(X,Y) := X_YD
#define GOVERNING_EQUATION		SET_FORMAT1(GOVERNING_EQUATION_NAME	, PHYSICAL_DOMAIN_DIMENSION)
#define INITIAL_CONDITION		SET_FORMAT1(INITIAL_CONDITION_NAME	, PHYSICAL_DOMAIN_DIMENSION)

//FORAMT2(X,Y) := X_Y
#define END_CONDITION			SET_FORMAT2(End_By					, END_CONDITION_NAME)<END_CONDITION_CONSTANT>		
#define POST_CONDITION			SET_FORMAT2(Post_By					, POST_CONDITION_NAME)<POST_CONDITION_CONSTANT>		

#define NUMERICAL_FLUX			NUMERICAL_FLUX_NAME<GOVERNING_EQUATION>
	